apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: mjolnir
  name: mjolnir-build
spec:
  resources:
    limits:
      memory: 3Gi
      cpu: "2"
  output:
    pushSecret:
      name: images-paas-pull-secret
    to:
      kind: DockerImage
      # TODO: change this from "thofman" to "mjolnir" organization
      name: images.paas.redhat.com/thofman/mjolnir:latest
  source:
    git:
      ref: master
      uri: https://github.com/jboss-set/mjolnir.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_MIRROR_URL
      - name: MAVEN_ARGS_APPEND
      - name: CUSTOM_INSTALL_DIRECTORIES
        value: extensions/*
      - name: ARTIFACT_DIR
        value: target
      - name: S2I_SOURCE_DEPLOYMENTS_FILTER
        value: '*.war'
      forcePull: true
      from:
        kind: ImageStreamTag
        name: eap72-openshift:latest
      incremental: true
      pullSecret:
        name: registry-redhat-io-pull-secret
    type: Source
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: eap72-openshift:latest
    type: ImageChange
  - type: ConfigChange
